name: Regression End-to-end tests

on:
  push  # Continua ouvindo push, mas vamos filtrar a execução

jobs:
  cypress-run:
    if: contains(github.event.head_commit.message, 'run-test')  # Só executa se o commit contiver essa frase
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5, 6]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests in parallel on Cloud
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          group: "Regression Tests - Parallel"
          ci-build-id: ${{ github.run_id }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
